### ISSUE TITLE
Beer objects appear to be linked in memory

### ISSUE THREAD

**Issue by jamrootz** [jamrootz/challenge100#1]
The program is supposed to generate a list of the 100 different beer objects as parsed from the html table.

**Problem**: each new object added to the list also overrides all previous objects.  I'm not sure why this happens as I am instantiating a NEW object each time and have verified it has different contents.

Help me @tjhladish !

**Comment by tjhladish** [comment]
The problem you're having is one of the more obnoxious things that Python does in my opinion.  On first inspection I thought the issue was the `beer = []` in your parser class, but it was actually `details = {}` in your `Beer` class.  Initialize `details` to `None`, and then in `__init__`, set `self.details = {}`.  What happening is that the details dictionary is actually persisting across calls to the constructor, so each time you call the constructor the details dictionary is being overwritten with new data.  I don't remember if you know C++, but this is like having a static class variable--without the clarity of calling it static.  I believe this kind of problem will come up with any mutable type.  Take a look at the first section of this page, it's related: http://docs.python-guide.org/en/latest/writing/gotchas/

Anyway, change your Beer class to this:

```
class Beer():
    details = None
    def __init__(self, catList, bList): # pass in list of categories from table headers
        self.details = {}
        for cat, element in zip(catList, bList):
            self.details[cat] = element
    def showDetails(self):
        for d in list(self.details.keys()): print(d,": ", self.details[d])
        print('\n\n')
```

**Comment by jamrootz** [comment]
Did you ever know that you're my hero?
